#!/bin/bash
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export TERM='xterm-256color'
export PATH="/home/docker/.composer/vendor/bin:$PATH"
export LC_CTYPE="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"
export SHELL=/bin/bash
export EDITOR=vim

#Alias
alias ls='ls --color'
alias ".."="cd .. && echo -e '\033[01;33m ~> $(pwd)\033[m'"
alias "..."="cd ../.. && echo -e '\033[01;33m ~> $(pwd)\033[m'" 
#PS1
function git_branch_name() {
  git branch 2>/dev/null | grep -e '^*' | sed -E 's/^\* (.+)$/(\1) /'
}

function show_colored_git_branch_in_prompt() {

  COPEN="\[\033[01;32m\]┌─[\[\033[m\]"
  CCLOSE="\[\033[01;32m\]]\[\033[m\]"
  LOGIN="\[\033[01;36m\] CLI#\u \[\033[m\]"
  HOST="\[\033[00;33m\]\h\[\033[m\]"
  DATA="\[\033[01;34m\][ $(date +%k:%M:%S) ]\[\033[m\]"
  LOCAL="\[\033[01;37m\][ \w ]\[\033[m\]"
  CURSORS="\[\033[01;32m\]~> \[\033[m\]"
  CURSOR="\[\033[01;32m\]\n└──> \[\033[m\]"
  BRANCH="\[\033[01;33m\]\$(git_branch_name)\[\033[m\]"
  PS1="${COPEN}${LOGIN}${CCLOSE} ${DATA} ${LOCAL}${CURSOR} ${BRANCH} ${TRACKER}"

}

show_colored_git_branch_in_prompt
